import Head from 'next/head'
import { Form, Button, Card, Alert, Modal } from 'react-bootstrap'
import Web3 from 'web3'
import { ethers, utils } from 'ethers'
import { useWallet } from 'use-wallet'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [token, setToken] = useState()
  const wallet = useWallet()

  const onSign = async () => {
    try {
      const { hash } = await (
        await fetch(`http://localhost:8080/hash/${wallet.account}`, {
          method: 'GET',
        })
      ).json()
      const provider = new ethers.providers.Web3Provider(wallet.ethereum, 'any')
      const signer = provider.getSigner()
      const message = utils.hashMessage(hash)
      const signature = await signer.signMessage(ethers.utils.arrayify(message))

      fetch(`http://localhost:8080/authenticate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          signature,
          message,
          address: wallet.account,
        }),
      })
        .then((res) => res.json())
        .then((res) => {
          setToken(res.token)
        })
        .catch((err) => console.log(err))
    } catch (err) {
      console.log(err)
      throw err
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Card className="p-3" style={{ width: '500px' }}>
          {token && <Alert variant="primary"> {token} </Alert>}
          {wallet?.status === 'connected' ? (
            <Button variant="primary" onClick={onSign}>
              {' '}
              Sign{' '}
            </Button>
          ) : (
            <Button variant="primary" onClick={() => wallet.connect()}>
              Connect Wallet
            </Button>
          )}
        </Card>
      </main>
    </div>
  )
}
